version: '3'

services:
  ss:
    image: shadowsocks/shadowsocks-libev
    command: ss-local -c /etc/shadowsocks-libev/config.json -u
    volumes:
      - ./ss-config.json:/etc/shadowsocks-libev/config.json

  polipo:
    image: vimagick/polipo
    command:
      socksParentProxy=ss:1086
      socksProxyType=socks5
    ports:
      - 1087:8123
